# Generated by Django 6.1 on 2026-08-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FIC", "Художественная"),
                            ("CLD", "Детская"),
                            ("SCI", "Научная"),
                            ("TEC", "Техническая"),
                            ("HIS", "Историческая"),
                            ("BIO", "Биография"),
                            ("POE", "Поэзия"),
                            ("DRA", "Драма"),
                        ],
                        max_length=3,
                    ),
                ),
                ("year", models.IntegerField()),
                ("pages", models.IntegerField()),
                ("total_copies", models.PositiveIntegerField(default=1)),
                ("available_copies", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="books.author"),
                ),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                    models.Index(fields=["year"], name="books_book_year_d303c9_idx"),
                ],
            },
        ),
    ]
