# Generated by Django 6.1 on 2026-08-07 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="borrowrecord",
            index=models.Index(fields=["status"], name="borrow_borr_status_c90689_idx"),
        ),
        migrations.AddIndex(
            model_name="borrowrecord",
            index=models.Index(
                fields=["due_date"], name="borrow_borr_due_dat_a372cc_idx"
            ),
        ),
    ]
